# Generated by Django 2.0.5 on 2018-07-18 00:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('bike_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Bike Id')),
            ],
            options={
                'verbose_name_plural': 'Bikes',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('rental_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Rental Id')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('bike_id', models.ForeignKey(db_column='bike_id', on_delete=django.db.models.deletion.CASCADE, related_name='bike_routes', to='webapp.Bikes', verbose_name='Bike Id')),
            ],
            options={
                'verbose_name_plural': 'Routes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Station Id')),
                ('station_name', models.CharField(max_length=500, verbose_name='Name')),
                ('location', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326, unique=True)),
                ('freq', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stations',
                'ordering': ['station_id'],
            },
        ),
        migrations.CreateModel(
            name='Stations_Pairs_Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastest_ref_dist', models.FloatField(blank=True, null=True, verbose_name='Fastest Ref Distance')),
                ('fastest_ref_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Faster Ref Time')),
                ('fastest_ref_geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('balanced_ref_dist', models.FloatField(blank=True, null=True, verbose_name='Balanced Ref Distance')),
                ('balanced_ref_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Balanced Ref Time')),
                ('balanced_ref_geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('quietest_ref_dist', models.FloatField(blank=True, null=True, verbose_name='Quietest Ref Distance')),
                ('quietest_ref_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quietest Ref Time')),
                ('quietest_ref_geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('freq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequency')),
                ('end_station_id', models.OneToOneField(db_column='end_station_id', on_delete=django.db.models.deletion.CASCADE, related_name='end_stations', to='webapp.Stations', verbose_name='End Station Id')),
                ('start_station_id', models.OneToOneField(db_column='start_station_id', on_delete=django.db.models.deletion.CASCADE, related_name='start_stations', to='webapp.Stations', verbose_name='Start Station Id')),
            ],
        ),
        migrations.AddField(
            model_name='routes',
            name='station_pairs_id',
            field=models.ForeignKey(db_column='station_pairs_id', on_delete=django.db.models.deletion.CASCADE, related_name='station_pairs', to='webapp.Stations_Pairs_Routes', verbose_name='Station Pairs Id'),
        ),
    ]
