# Generated by Django 2.0.5 on 2018-07-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations_pairs_routes',
            name='fastest_ref_dist',
        ),
        migrations.RemoveField(
            model_name='stations_pairs_routes',
            name='fastest_ref_geom',
        ),
        migrations.RemoveField(
            model_name='stations_pairs_routes',
            name='fastest_ref_time',
        ),
        migrations.RemoveField(
            model_name='stations_pairs_routes',
            name='quietest_ref_dist',
        ),
        migrations.RemoveField(
            model_name='stations_pairs_routes',
            name='quietest_ref_geom',
        ),
        migrations.RemoveField(
            model_name='stations_pairs_routes',
            name='quietest_ref_time',
        ),
    ]
